version: '3.9'
services:
  api:
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    command: sh -c "wait-for postgres:5432 mongo:27017 -- /start-reload.sh"
    depends_on:
      - postgres
    networks:
      - back-end
    ports:
      - 5000:80
    restart: unless-stopped
    volumes:
      - .:/app

  mongo:
    image: mongo
    networks:
      - back-end
    ports:
      - 27017:27017
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: dio
      POSTGRES_PASSWORD: dio
    networks:
      - back-end
    ports:
      - 5432:5432
    restart: unless-stopped

networks:
  back-end:
    name: 'back-end'
  front-end:
    name: 'front-end'
