[tool.poetry]
name = "aceleracao-dio-backend"
version = "0.1.0"
description = "Aceleração DIO Backend"
authors = ["Developers <developers@koper.com.br>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
